# Generated by Django 4.2.11 on 2024-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_unit',
            name='course_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
