# Generated by Django 4.2.11 on 2024-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_course_unit_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_unit',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
