# Generated by Django 4.2.11 on 2024-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_course_unit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_unit',
            name='file_name',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
