# Generated by Django 4.2.11 on 2024-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_course_unit_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_unit',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
