# Generated by Django 4.2.11 on 2024-07-10 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_remove_course_unit_file_name_remove_uploadfile_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
