# Generated by Django 4.2.11 on 2024-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_uploadfile_file_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
